# Generated by Django 5.1.3 on 2024-11-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='bet',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bet',
            name='date',
            field=models.DateField(default='2024-01-01', verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.CharField(default='Sem partida', max_length=100),
        ),
        migrations.AddField(
            model_name='bet',
            name='odd',
            field=models.FloatField(default=1.0, verbose_name='Odd'),
        ),
        migrations.AddField(
            model_name='bet',
            name='result',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ganhou', 'Ganhou'), ('Perdeu', 'Perdeu'), ('Empatou', 'Empatou')], default='Pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='bet',
            name='stake',
            field=models.FloatField(default=0.0, verbose_name='Stake'),
        ),
    ]
